# Generated by Django 6.0.1 on 2026-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("PENDING", "Pending"),
                ],
                max_length=20,
            ),
        ),
    ]
