# Generated by Django 6.0.1 on 2026-01-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("available_slots", models.PositiveIntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="trips/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
