# Generated by Django 6.0.1 on 2026-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="trip_images/"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="location",
            field=models.CharField(max_length=150),
        ),
    ]
