# Generated by Django 6.0.1 on 2026-01-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_image_alter_trip_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="image",
        ),
        migrations.AddField(
            model_name="trip",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="trip_images/cover/"
            ),
        ),
        migrations.CreateModel(
            name="TripImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="trip_images/gallery/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
    ]
