# Generated by Django 6.0.1 on 2026-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_remove_trip_image_alter_trip_location_tripimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="trip_images/cover/"
            ),
        ),
        migrations.AlterField(
            model_name="tripimage",
            name="image",
            field=models.ImageField(upload_to="trip_images/gallery/"),
        ),
    ]
